import { ArkPassiveResult } from '@/types/ark_passive';

export const DUMMY_ARK_PASSIVE: { result: ArkPassiveResult } = {
  result: {
    ui_type: 'ARK_PASSIVE',
    data: {
      ark_passive_effects_tb: [
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_17.png',
          tier: '1티어',
          effect_name: '완벽한 화음',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_3.png',
          tier: '2티어',
          effect_name: '절실한 구원',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_01/ark_passive_01_33.png',
          tier: '3티어',
          effect_name: '포용의 세레나데',
          level: 1,
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_7.png',
          tier: '3티어',
          effect_name: '증폭의 세레나데',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_9.png',
          tier: '4티어',
          effect_name: '낙인의 세레나데',
          level: 1,
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_18.png',
          tier: '4티어',
          effect_name: '세레나데 코드',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_2.png',
          tier: '1티어',
          effect_name: '특화',
          level: 14,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_4.png',
          tier: '1티어',
          effect_name: '신속',
          level: 26,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_19.png',
          tier: '2티어',
          effect_name: '축복의 여신',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_33.png',
          tier: '3티어',
          effect_name: '정열의 춤사위',
          level: 2,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_42.png',
          tier: '4티어',
          effect_name: '선각자',
          level: 1,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_45.png',
          tier: '4티어',
          effect_name: '기원',
          level: 1,
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_evolution/ark_passive_evolution_18.png',
          tier: '5티어',
          effect_name: '입식 타격가',
          level: 2,
        },
        {
          character_name: '첫번째도구',
          name: '도약',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_02/ark_passive_02_1.png',
          tier: '1티어',
          effect_name: '충전된 분노',
          level: 2,
        },
        {
          character_name: '첫번째도구',
          name: '도약',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_01/ark_passive_01_54.png',
          tier: '1티어',
          effect_name: '각성 증폭기',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '도약',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_01/ark_passive_01_10.png',
          tier: '1티어',
          effect_name: '잠재력 해방',
          level: 5,
        },
        {
          character_name: '첫번째도구',
          name: '도약',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_02/ark_passive_02_5.png',
          tier: '1티어',
          effect_name: '즉각적인 주문',
          level: 3,
        },
        {
          character_name: '첫번째도구',
          name: '도약',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ark_passive_bd/ark_passive_bd_11.png',
          tier: '2티어',
          effect_name: '풍요의 랩소디',
          level: 3,
        },
      ],
      ark_passive_points_tb: [
        {
          character_name: '첫번째도구',
          name: '도약',
          value: 70,
          description: '6랭크 21레벨',
        },
        {
          character_name: '첫번째도구',
          name: '진화',
          value: 140,
          description: '6랭크 26레벨',
        },
        {
          character_name: '첫번째도구',
          name: '깨달음',
          value: 101,
          description: '6랭크 26레벨',
        },
      ],
    },
  },
};
