import { AvatarResult } from '@/types/avatar';

export const DUMMY_AVATAR: { result: AvatarResult } = {
  result: {
    ui_type: 'AVATAR',
    data: {
      armory_avatars_tb: [
        {
          character_name: '첫번째도구',
          type: '무기 아바타',
          name: '질서의 영원 리아네 하프',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_7464.png',
          grade: '전설',
          is_set: false,
          is_inner: true,
          basic_effect: '지능 +2.00%',
          tendency_stat: '지성 : 5 담력 : 5 매력 : 5 친절 : 5',
          source: '[요즈의 항아리] 요즈 III : 영원',
        },
        {
          character_name: '첫번째도구',
          type: '머리 아바타',
          name: '질서의 영원 머리',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_7458.png',
          grade: '전설',
          is_set: false,
          is_inner: true,
          basic_effect: '지능 +2.00%',
          tendency_stat: '지성 : 5 담력 : 5 매력 : 5 친절 : 5',
          source: '[요즈의 항아리] 요즈 III : 영원',
        },
        {
          character_name: '첫번째도구',
          type: '상의 아바타',
          name: '치명적인 도약 상의',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_4616.png',
          grade: '전설',
          is_set: false,
          is_inner: true,
          basic_effect: '지능 +2.00%',
          tendency_stat: '지성 : 10 담력 : 5 매력 : 5 친절 : 5',
          source: '[요즈의 항아리] 요즈 II : 도약',
        },
        {
          character_name: '첫번째도구',
          type: '하의 아바타',
          name: '치명적인 도약 하의',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_4617.png',
          grade: '전설',
          is_set: false,
          is_inner: true,
          basic_effect: '지능 +2.00%',
          tendency_stat: '지성 : 5 담력 : 5 매력 : 10 친절 : 5',
          source: '[요즈의 항아리] 요즈 II : 도약',
        },
        {
          character_name: '첫번째도구',
          type: '얼굴1 아바타',
          name: '6주년 여정 얼굴1 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9048.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: null,
          tendency_stat: '매력 : 5',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '얼굴2 아바타',
          name: '6주년 여정 얼굴2 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9049.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: null,
          tendency_stat: '친절 : 5',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '무기 아바타',
          name: '6주년 여정 리아네 하프 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9121.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: '지능 +1.00%',
          tendency_stat: '매력 : 10 친절 : 5',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '머리 아바타',
          name: '6주년 여정 머리 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9045.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: '지능 +1.00%',
          tendency_stat: '매력 : 15',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '상의 아바타',
          name: '6주년 여정 상의 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9046.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: '지능 +1.00%',
          tendency_stat: '친절 : 20',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '하의 아바타',
          name: '6주년 여정 하의 (이벤트)',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/shop_icon/shop_icon_9047.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: '지능 +1.00%',
          tendency_stat: '매력 : 20',
          source: null,
        },
        {
          character_name: '첫번째도구',
          type: '이동 효과',
          name: '호호 군고구마 이동 효과',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/moving_effect/moving_effect_41.png',
          grade: '영웅',
          is_set: false,
          is_inner: false,
          basic_effect: null,
          tendency_stat: null,
          source: null,
        },
      ],
      armory_profile_tb: [
        {
          character_name: '첫번째도구',
          server_name: '카단',
          character_class_name: '바드',
          character_level: 70,
          item_avg_level: 1765.83,
          combat_power: 4665.57,
          character_image:
            'https://img.lostark.co.kr/armory/4/87E28987069012505B0F1FC57546161164226B75E1A45B96627F5748469B4AE3.jpg?v=20260316094818',
          expedition_level: 337,
          town_level: 70,
          town_name: '펜토르',
          title: '죽음의 현신',
          guild_member_grade: '일반 길드원',
          guild_name: '혈석먹고꼬북',
          using_skill_point: 480,
          total_skill_point: 483,
          honor_point: 37,
          stat_atk: 190848,
          stat_hp: 372275,
          stat_crit: 73,
          stat_spec: 847,
          stat_swift: 1634,
          stat_dom: 79,
          stat_end: 71,
          stat_exp: 75,
          tend_intellect: 670,
          tend_courage: 676,
          tend_charm: 597,
          tend_kindness: 621,
          updated_at: '2026-03-16T11:24:36.273329',
        },
      ],
    },
  },
};
