import { ProfileResult } from '@/types/profile';

export const DUMMY_PROFILE: { result: ProfileResult } = {
  result: {
    ui_type: 'PROFILE',
    data: {
      armory_profile_tb: [
        {
          character_name: '첫번째도구',
          server_name: '카단',
          character_class_name: '바드',
          character_level: 70,
          item_avg_level: 1765.83,
          combat_power: 4665.57,
          character_image:
            'https://img.lostark.co.kr/armory/4/87E28987069012505B0F1FC57546161164226B75E1A45B96627F5748469B4AE3.jpg?v=20260316094818',
          expedition_level: 337,
          town_level: 70,
          town_name: '펜토르',
          title: '죽음의 현신',
          guild_member_grade: '일반 길드원',
          guild_name: '혈석먹고꼬북',
          using_skill_point: 480,
          total_skill_point: 483,
          honor_point: 37,
          stat_atk: 190848,
          stat_hp: 372275,
          stat_crit: 73,
          stat_spec: 847,
          stat_swift: 1634,
          stat_dom: 79,
          stat_end: 71,
          stat_exp: 75,
          tend_intellect: 670,
          tend_courage: 676,
          tend_charm: 597,
          tend_kindness: 621,
          updated_at: '2026-03-16T11:24:36.273329',
        },
      ],
      armory_equipment_tb: [
        {
          character_name: '첫번째도구',
          type: '무기',
          name: '+20 운명의 전율 리아네 하프',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_210.png',
          grade: '고대',
          enhancement_level: 20,
          quality: 93,
          item_tier: 4,
          basic_effect: '무기 공격력 +213333',
          additional_effect: '추가 피해 +27.30%',
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '투구',
          name: '+18 운명의 전율 머리장식',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_202.png',
          grade: '고대',
          enhancement_level: 18,
          quality: 94,
          item_tier: 4,
          basic_effect:
            '물리 방어력 +9614마법 방어력 +10683지능 +117218체력 +11270',
          additional_effect: '생명 활성력 +1238',
          ark_passive_effect: '진화 +24',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '상의',
          name: '+18 운명의 전율 상의',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_198.png',
          grade: '고대',
          enhancement_level: 18,
          quality: 96,
          item_tier: 4,
          basic_effect:
            '물리 방어력 +12819마법 방어력 +11751지능 +93775체력 +15027',
          additional_effect: '생명 활성력 +1291',
          ark_passive_effect: '진화 +24',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '하의',
          name: '+18 운명의 전율 하의',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_199.png',
          grade: '고대',
          enhancement_level: 18,
          quality: 98,
          item_tier: 4,
          basic_effect:
            '물리 방어력 +11751마법 방어력 +12819지능 +101310체력 +12773',
          additional_effect: '생명 활성력 +1345',
          ark_passive_effect: '진화 +24',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '장갑',
          name: '+18 운명의 전율 장갑',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_201.png',
          grade: '고대',
          enhancement_level: 18,
          quality: 98,
          item_tier: 4,
          basic_effect:
            '물리 방어력 +8546마법 방어력 +8546지능 +140662체력 +7514',
          additional_effect: '생명 활성력 +1345',
          ark_passive_effect: '진화 +24',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '어깨',
          name: '+18 운명의 전율 어깨장식',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/sm_item/sm_item_01_200.png',
          grade: '고대',
          enhancement_level: 18,
          quality: 95,
          item_tier: 4,
          basic_effect:
            '물리 방어력 +10683마법 방어력 +9614지능 +124754체력 +9768',
          additional_effect: '생명 활성력 +1264',
          ark_passive_effect: '진화 +24',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '목걸이',
          name: '도래한 결전의 목걸이',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_215.png',
          grade: '고대',
          enhancement_level: 0,
          quality: 76,
          item_tier: 4,
          basic_effect: '힘 +15580민첩 +15580지능 +15580체력 +3901',
          additional_effect:
            '적에게 주는 피해 +0.55%세레나데, 신앙, 조화 게이지 획득량 +3.60%낙인력 +8.00%',
          ark_passive_effect: '깨달음 +13',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '귀걸이',
          name: '도래한 결전의 귀걸이',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_115.png',
          grade: '고대',
          enhancement_level: 0,
          quality: 88,
          item_tier: 4,
          basic_effect: '힘 +13660민첩 +13660지능 +13660체력 +2780',
          additional_effect:
            '파티원 보호막 효과 +0.95%무기 공격력 +3.00%최대 생명력 +3250',
          ark_passive_effect: '깨달음 +12',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '귀걸이',
          name: '도래한 결전의 귀걸이',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_115.png',
          grade: '고대',
          enhancement_level: 0,
          quality: 85,
          item_tier: 4,
          basic_effect: '힘 +13119민첩 +13119지능 +13119체력 +2800',
          additional_effect:
            '무기 공격력 +3.00%파티원 회복 효과 +2.10%최대 생명력 +1300',
          ark_passive_effect: '깨달음 +12',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '반지',
          name: '마주한 종언의 반지',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_21.png',
          grade: '고대',
          enhancement_level: 0,
          quality: 85,
          item_tier: 4,
          basic_effect: '힘 +12627민첩 +12627지능 +12627체력 +2198',
          additional_effect:
            '아군 피해량 강화 효과 +7.50%전투 중 생명력 회복량 +25아군 공격력 강화 효과 +3.00%',
          ark_passive_effect: '깨달음 +12',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '반지',
          name: '도래한 결전의 반지',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_22.png',
          grade: '고대',
          enhancement_level: 0,
          quality: 81,
          item_tier: 4,
          basic_effect: '힘 +12356민첩 +12356지능 +12356체력 +2178',
          additional_effect:
            '아군 피해량 강화 효과 +7.50%최대 마나 +15아군 공격력 강화 효과 +3.00%',
          ark_passive_effect: '깨달음 +12',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '어빌리티 스톤',
          name: '위대한 비상의 돌',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/ability/ability_246.png',
          grade: '고대',
          enhancement_level: 0,
          quality: -1,
          item_tier: 4,
          basic_effect: '체력 +23481',
          additional_effect:
            '[각성] Lv.2, [구슬동자] Lv.3, [공격력 감소] Lv.0, [레벨 보너스] 기본 공격력 +1.50%',
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '팔찌',
          name: '찬란한 구원자의 팔찌',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_327.png',
          grade: '고대',
          enhancement_level: 0,
          quality: -1,
          item_tier: 4,
          basic_effect: null,
          additional_effect:
            '특화 +72 신속 +97 지능 +13504 몬스터에게 공격 적중 시 8초 동안 대상의 치명타 저항을 2.1% 감소시킨다.해당 효과는 한 파티 당 하나만 적용된다.아군 공격력 강화 효과가 2.5% 증가한다.몬스터에게 공격 적중 시 8초 동안 대상의 치명타 피해 저항을 4.2% 감소시킨다.해당 효과는 한 파티 당 하나만 적용된다.아군 공격력 강화 효과가 2.5% 증가한다.',
          ark_passive_effect: '도약 +18',
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '나침반',
          name: '특제 성운 나침반',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_312.png',
          grade: '유물',
          enhancement_level: 0,
          quality: -1,
          item_tier: null,
          basic_effect: null,
          additional_effect:
            '모든 선박의 최종 내구도 수리 비용 +20.00% 감소섬에서 이동 속도 +10.00%선박 통상 운항 속도(노트) +4.0',
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '부적',
          name: '광휘의 별무리 부적',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_308.png',
          grade: '유물',
          enhancement_level: 0,
          quality: -1,
          item_tier: null,
          basic_effect: null,
          additional_effect:
            '채집 속도 +4.00%내구도 미차감 확률 +6.40%모든 생활 전체 등급 재료 획득률 +30.00%',
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '문장',
          name: '백금 용사의 문장',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_320.png',
          grade: '유물',
          enhancement_level: 0,
          quality: -1,
          item_tier: null,
          basic_effect: null,
          additional_effect:
            "모험가에게 피격 시 '단단함' 효과 획득 단단함: 8초 동안 받는 피해 15% 감소 (재사용 대기시간 40초)모험가에게 피격 시 '조급함' 효과 획득 조급함: 5초 동안 이동 속도 3% 증가, 스킬 재사용 대기시간 5% 감소, 최대 3회 중첩 가능피격이상 및 상태이상 중 모험가에게 피격 시 '기사회생' 효과 획득 기사회생: 5초 동안 기상기 재사용 대기시간 20% 감소 (재사용 대기시간 30초)",
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
        {
          character_name: '첫번째도구',
          type: '보주',
          name: '온화한 투영의 보주',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/acc/acc_334.png',
          grade: '유물',
          enhancement_level: 0,
          quality: -1,
          item_tier: null,
          basic_effect: null,
          additional_effect: null,
          ark_passive_effect: null,
          advanced_reinforcement: 0,
        },
      ],
      armory_card_tb: [
        {
          character_name: '첫번째도구',
          slot: 0,
          name: '세리아',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_rare/card_rare_02_1.png',
          grade: '희귀',
          awake_count: 5,
          awake_total: 5,
          description:
            '착하고 맑은 성품을 지닌 세이크리아 교단의 사제. 습격 받은 사람들을 정성스럽게 돌보고 있다.',
        },
        {
          character_name: '첫번째도구',
          slot: 1,
          name: '집행관 솔라스',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_uncommon/card_uncommon_01_4.png',
          grade: '고급',
          awake_count: 5,
          awake_total: 5,
          description:
            '세이크리아의 냉정한 집행관. 죄 없는 사람들을 사교도로 판단하여 처단함으로써 되돌릴 수 없는 일을 저지르고 만다.',
        },
        {
          character_name: '첫번째도구',
          slot: 2,
          name: '국왕 실리안',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_legend/card_legend_00_3.png',
          grade: '전설',
          awake_count: 5,
          awake_total: 5,
          description:
            '루테란의 국왕. 진정한 왕으로서 백성을 위해 끊임없이 고민한다.',
        },
        {
          character_name: '첫번째도구',
          slot: 3,
          name: '데런 아만',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_legend/card_legend_00_6.png',
          grade: '전설',
          awake_count: 5,
          awake_total: 5,
          description:
            '숨기고 있던 데런의 힘을 개방한 아만의 모습. 신성력이 아닌, 내면에 깃든 악마의 힘을 사용한다.',
        },
        {
          character_name: '첫번째도구',
          slot: 4,
          name: '카마인',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_legend/card_legend_01_3.png',
          grade: '전설',
          awake_count: 5,
          awake_total: 5,
          description:
            '무엇을 생각하는지 알 수 없는 음험한 악마. 다른 악마의 힘을 흡수할 수 있는 신비한 능력을 지니고 있다.',
        },
        {
          character_name: '첫번째도구',
          slot: 5,
          name: '아만',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/card_legend/card_legend_00_0.png',
          grade: '전설',
          awake_count: 5,
          awake_total: 5,
          description:
            '중간계를 지키고 사람들을 치유하기 위해 세상에 흩어진 아크를 찾고 있는 젊은 사제.',
        },
      ],
      armory_card_effects_tb: [
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 2세트',
          description: '암속성 피해 감소 +8.00%',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 4세트',
          description: '암속성 피해 감소 +8.00%',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 6세트',
          description: '암속성 피해 감소 +9.00%',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 6세트 (12각성합계)',
          description: '치명타 적중률 +7.00%',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 6세트 (18각성합계)',
          description:
            '공격 적중 시 대상이 자신 및 파티원에게 받는 성속성 피해량이 1.0% 증가',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 6세트 (24각성합계)',
          description:
            '공격 적중 시 대상이 자신 및 파티원에게 받는 성속성 피해량이 1.0% 증가',
        },
        {
          character_name: '첫번째도구',
          effect_name: '남겨진 바람의 절벽 6세트 (30각성합계)',
          description:
            '공격 적중 시 대상이 자신 및 파티원에게 받는 성속성 피해량이 1.5% 증가',
        },
      ],
      armory_gem_effects_tb: [
        {
          character_name: '첫번째도구',
          description: '기본 공격력 총합 : 9.40%',
        },
      ],
      armory_gem_tb: [
        {
          character_name: '첫번째도구',
          slot: 0,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '사운드 홀릭',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 1,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '윈드 오브 뮤직',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 2,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '소나티네',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 3,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '빛의 광시곡',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 4,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '음파 진동',
          effect_type: '피해 40.00% 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 5,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '천상의 연주',
          effect_type: '피해 40.00% 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 6,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '세레나데 스킬',
          effect_type: '지원 효과 9.00 % 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 7,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '수호의 연주',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 8,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '천상의 연주',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 9,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '리듬 벅샷',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 10,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '음파 진동',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
      ],
    },
  },
};
