import { SkillResult } from '@/types/skill';

export const DUMMY_SKILLS: { result: SkillResult } = {
  result: {
    ui_type: 'SKILL',
    data: {
      armory_skills_tb: [
        {
          character_name: '첫번째도구',
          skill_name: '소나티네',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_26.png',
          skill_level: 10,
          type: '일반',
          skill_type: '0',
          cooldown: 21,
          mana_cost: 533,
          weak_point: 1,
          stagger: '하',
          attack_type: null,
          is_counter: false,
          tripod_1_name: '빠른 준비',
          tripod_2_name: '음표 낙인',
          tripod_3_name: '선율 증가',
          rune_name: '속행',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "소나티네"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 21초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_26.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 10"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 533 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>전방 바닥으로 두개의 오선지를 그리며 적들을 밀어내며, <FONT COLOR=\'#00ccff\'>111,346</FONT>, <FONT COLOR=\'#00ccff\'>111,346</FONT>, <FONT COLOR=\'#00ccff\'>1,367,474</FONT>의 피해를 준다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 하</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>재사용 대기시간이 <FONT COLOR=\'#99ff99\'>7.0</FONT>초 감소한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>빠른 준비</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_56.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>[성] 속성으로 변경되고, 소나티네에 적중된 적에게 <FONT COLOR=\'#ffff99\'>10.0</FONT>초간 음표 낙인이 생겨 자신 및 파티원이 주는 피해가 <FONT COLOR=\'#99ff99\'>10.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>음표 낙인</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_76.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>적중 시 획득하는 세레나데 게이지가 <FONT COLOR=\'#99ff99\'>225.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>선율 증가</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_64.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>속행</FONT>] 스킬 사용 시 일정 확률로 전체 재사용 대기 시간이 16% 감소"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>소나티네</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  },\r\n  "Element_009": {\r\n    "type": "BlinkLineStart",\r\n    "value": true\r\n  },\r\n  "Element_010": {\r\n    "type": "SingleTextBox",\r\n    "value": "다음 스킬 레벨 11"\r\n  },\r\n  "Element_011": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 레벨</FONT> 55"\r\n  },\r\n  "Element_012": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 스킬 포인트 </FONT>6"\r\n  },\r\n  "Element_013": {\r\n    "type": "SingleTextBox",\r\n    "value": "마나 533 소모"\r\n  },\r\n  "Element_014": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>전방 바닥으로 두개의 오선지를 그리며 적들을 밀어내며, <FONT COLOR=\'#00ccff\'>121,032</FONT>, <FONT COLOR=\'#00ccff\'>121,032</FONT>, <FONT COLOR=\'#00ccff\'>1,487,434</FONT>의 피해를 준다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 하</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_015": {\r\n    "type": "BlinkLineEnd",\r\n    "value": true\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '사운드 홀릭',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_11.png',
          skill_level: 10,
          type: '일반',
          skill_type: '0',
          cooldown: 24,
          mana_cost: 569,
          weak_point: 0,
          stagger: '중',
          attack_type: '백 어택 슈퍼아머',
          is_counter: false,
          tripod_1_name: '마나 치유',
          tripod_2_name: '지속력 강화',
          tripod_3_name: '선율 증가',
          rune_name: '풍요',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "사운드 홀릭"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 24초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_11.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 10"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 569 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>강력한 빛줄기를 내뿜어 <FONT COLOR=\'#ffff99\'>3</FONT>초 동안 <FONT COLOR=\'#ffff99\'>0.3</FONT>초 마다 <FONT COLOR=\'#00ccff\'>127,009</FONT>의 피해를 <FONT COLOR=\'#ffff99\'>10</FONT>회 준다. 방향 전환을 자유롭게 할 수 있지만 이동을 하면 시전이 취소된다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 중</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 백 어택</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>사운드 홀릭에 적중된 자신 및 파티원의 마나를 <FONT COLOR=\'#99ff99\'>0.5%</FONT> 씩 회복시킨다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>마나 치유</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_79.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>지속 시간이 <FONT COLOR=\'#99ff99\'>1.5</FONT>초 증가하여 판정횟수가 <FONT COLOR=\'#ffff99\'>5</FONT>회 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>지속력 강화</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_42.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>적중 시 획득하는 세레나데 게이지가 <FONT COLOR=\'#99ff99\'>300.0%</FONT> 증가하며, 지속 시간이 <FONT COLOR=\'#ff9999\'>50.0%</FONT> 감소한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>선율 증가</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_64.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>풍요</FONT>] 스킬 적중 시 아이덴티티 게이지 획득량 40% 증가"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>사운드 홀릭</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  },\r\n  "Element_009": {\r\n    "type": "BlinkLineStart",\r\n    "value": true\r\n  },\r\n  "Element_010": {\r\n    "type": "SingleTextBox",\r\n    "value": "다음 스킬 레벨 11"\r\n  },\r\n  "Element_011": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 레벨</FONT> 55"\r\n  },\r\n  "Element_012": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 스킬 포인트 </FONT>6"\r\n  },\r\n  "Element_013": {\r\n    "type": "SingleTextBox",\r\n    "value": "마나 569 소모"\r\n  },\r\n  "Element_014": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>강력한 빛줄기를 내뿜어 <FONT COLOR=\'#ffff99\'>3</FONT>초 동안 <FONT COLOR=\'#ffff99\'>0.3</FONT>초 마다 <FONT COLOR=\'#00ccff\'>138,223</FONT>의 피해를 <FONT COLOR=\'#ffff99\'>10</FONT>회 준다. 방향 전환을 자유롭게 할 수 있지만 이동을 하면 시전이 취소된다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 중</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 백 어택</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_015": {\r\n    "type": "BlinkLineEnd",\r\n    "value": true\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '수호의 연주',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_21.png',
          skill_level: 14,
          type: '일반',
          skill_type: '0',
          cooldown: 30,
          mana_cost: 636,
          weak_point: 0,
          stagger: null,
          attack_type: null,
          is_counter: false,
          tripod_1_name: '강인함',
          tripod_2_name: '끝나지 않는 수호',
          tripod_3_name: '수호의 바람',
          rune_name: '집중',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "수호의 연주"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 30초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_21.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 14"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 636 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>하프를 연주해 자신 및 <FONT COLOR=\'#ffff99\'>24m</FONT> 범위 내에 있는 파티원의 받는 피해를 <FONT COLOR=\'#ffff99\'>8</FONT>초간 <FONT COLOR=\'#99ff99\'>32.0%</FONT> 감소시킨다.</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>수호의 연주 사용 중 피격이상에 면역이 된다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>강인함</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_23.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>수호의 연주 버프가 유지시간에 의해 종료되면, <FONT COLOR=\'#ffff99\'>8.0</FONT>초간 자신의 최대 생명력의 <FONT COLOR=\'#99ff99\'>20.0%</FONT>에 해당하는 보호막을 추가로 생성한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>끝나지 않는 수호</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_75.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>상태이상 공격을 <FONT COLOR=\'#99ff99\'>1</FONT>회 막아준다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>수호의 바람</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_65.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>집중</FONT>] 스킬 사용 시 마나 소모 40% 감소"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>수호의 연주</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '천상의 연주',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_12.png',
          skill_level: 14,
          type: '일반',
          skill_type: '0',
          cooldown: 30,
          mana_cost: 636,
          weak_point: 0,
          stagger: null,
          attack_type: '백 어택 슈퍼아머',
          is_counter: false,
          tripod_1_name: '빠른 준비',
          tripod_2_name: '용맹의 연주',
          tripod_3_name: '격렬한 연주',
          rune_name: '질풍',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "천상의 연주"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 30초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_12.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 14"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 636 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>주변에 <FONT COLOR=\'#00ccff\'>778,970</FONT>의 피해를 주고 <FONT COLOR=\'#ffff99\'>8</FONT>초간 자신 및 <FONT COLOR=\'#ffff99\'>24.0m</FONT> 범위 안에 있는 파티원의 공격력에 버프 시전자의 기본 공격력의 <FONT COLOR=\'#99ff99\'>12.0%</FONT>만큼 더해지며, 공격속도를 <FONT COLOR=\'#99ff99\'>8.0%</FONT>, 마나 회복 속도를 <FONT COLOR=\'#99ff99\'>40%</FONT> 증가시킨다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 백 어택</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>재사용 대기시간이 <FONT COLOR=\'#99ff99\'>6.0</FONT>초 감소한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>빠른 준비</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_56.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>적중 시 적의 공격력을 <FONT COLOR=\'#ffff99\'>9.0</FONT>초간 <FONT COLOR=\'#99ff99\'>35.4%</FONT> 감소시킨다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>용맹의 연주</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_46.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>자신 및 파티원에게 적용되는 버프 시전자의 기본 공격력에 기반한 공격력 증가 효과가 <FONT COLOR=\'#99ff99\'>10.0%</FONT> 추가로 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>격렬한 연주</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_1.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>질풍</FONT>] 스킬 시전 속도가 14% 증가"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>천상의 연주</FONT> 재사용 대기시간 20.00% 감소 <BR>[바드] <FONT COLOR=\'#FFD200\'>천상의 연주</FONT> 피해 40.00% 증가 <BR>[바드] <FONT COLOR=\'#FFD200\'>천상의 연주</FONT> 지원 효과 9.00 % 증가 "\r\n    }\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '리듬 벅샷',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_9.png',
          skill_level: 10,
          type: '일반',
          skill_type: '0',
          cooldown: 16,
          mana_cost: 469,
          weak_point: 1,
          stagger: '중',
          attack_type: '헤드 어택',
          is_counter: true,
          tripod_1_name: '선율 증가',
          tripod_2_name: '강인함',
          tripod_3_name: '날렵한 시전',
          rune_name: '정화',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "리듬 벅샷"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 16초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_9.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 10"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 469 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>하프를 강하게 당겨 음표를 터트려 명중된 적에게 <FONT COLOR=\'#00ccff\'>853,142</FONT>의 피해를 주고 날려보낸다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 중</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 헤드 어택</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>카운터 : 가능</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>적중 시 회복하는 세레나데 게이지가 <FONT COLOR=\'#99ff99\'>45.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>선율 증가</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_64.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>시전 중 피격이상에 면역이 된다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>강인함</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_23.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>시전 속도가 <FONT COLOR=\'#99ff99\'>20.0%</FONT> 증가하고 치명타 적중률이 <FONT COLOR=\'#99ff99\'>80.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>날렵한 시전</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_6.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>정화</FONT>] 스킬 사용 시 80% 확률로 자신에게 걸린 해로운 효과 1개 제거"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>리듬 벅샷</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  },\r\n  "Element_009": {\r\n    "type": "BlinkLineStart",\r\n    "value": true\r\n  },\r\n  "Element_010": {\r\n    "type": "SingleTextBox",\r\n    "value": "다음 스킬 레벨 11"\r\n  },\r\n  "Element_011": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 레벨</FONT> 55"\r\n  },\r\n  "Element_012": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 스킬 포인트 </FONT>6"\r\n  },\r\n  "Element_013": {\r\n    "type": "SingleTextBox",\r\n    "value": "마나 469 소모"\r\n  },\r\n  "Element_014": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>하프를 강하게 당겨 음표를 터트려 명중된 적에게 <FONT COLOR=\'#00ccff\'>927,905</FONT>의 피해를 주고 날려보낸다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 중</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 헤드 어택</FONT></FONT>"\r\n  },\r\n  "Element_015": {\r\n    "type": "BlinkLineEnd",\r\n    "value": true\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '음파 진동',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_13.png',
          skill_level: 14,
          type: '지점',
          skill_type: '0',
          cooldown: 24,
          mana_cost: 569,
          weak_point: 2,
          stagger: '중상',
          attack_type: null,
          is_counter: false,
          tripod_1_name: '강인함',
          tripod_2_name: '광휘의 음파',
          tripod_3_name: '넓은 공격',
          rune_name: '질풍',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "음파 진동"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 24초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFD200\'>지점</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_13.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 14"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 569 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>지정한 위치에 있는 적에게 <FONT COLOR=\'#00ccff\'>659,497</FONT>의 피해를 주고 공중에 띄우고, 지면으로 내리 꽂아 <FONT COLOR=\'#00ccff\'>1,648,650</FONT>의 피해를 주고, 잔류물이 남아 <FONT COLOR=\'#ffff99\'>3.0</FONT>초간 <FONT COLOR=\'#00ccff\'>247,457</FONT>의 피해를 <FONT COLOR=\'#ffff99\'>4</FONT>회 주며, 자신 및 파티원이 음파 진동 영역 및 잔류물 영역에 들어오면 <FONT COLOR=\'#ffff99\'>2</FONT>초 동안 공격력이 버프 시전자의 기본 공격력의 <FONT COLOR=\'#99ff99\'>12.0%</FONT>만큼 더해진다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 2</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>무력화 : 중상</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>음파 진동 사용 중 피격이상에 면역이 된다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>강인함</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_23.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>[성] 속성으로 변경되고, 자신 및 파티원에게 적용되는 버프 시전자의 기본 공격력에 기반한 공격력 증가 효과가 <FONT COLOR=\'#99ff99\'>10.0%</FONT> 추가로 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>광휘의 음파</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_18.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>음파 진동의 구체가 커져 판정 범위가 <FONT COLOR=\'#99ff99\'>40.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>넓은 공격</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_7.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>질풍</FONT>] 스킬 시전 속도가 14% 증가"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>음파 진동</FONT> 재사용 대기시간 20.00% 감소 <BR>[바드] <FONT COLOR=\'#FFD200\'>음파 진동</FONT> 피해 40.00% 증가 <BR>[바드] <FONT COLOR=\'#FFD200\'>음파 진동</FONT> 지원 효과 9.00 % 증가 "\r\n    }\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '빛의 광시곡',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_22.png',
          skill_level: 10,
          type: '지점',
          skill_type: '0',
          cooldown: 24,
          mana_cost: 569,
          weak_point: 1,
          stagger: null,
          attack_type: null,
          is_counter: false,
          tripod_1_name: '빠른 준비',
          tripod_2_name: '안정된 빛',
          tripod_3_name: '빛의 보호',
          rune_name: '수호',
          rune_grade: '전설',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "빛의 광시곡"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 24초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFD200\'>지점</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_22.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 10"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 569 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>마우스 위치에 아름다운 선율의 음파를 소환해 <FONT COLOR=\'#ffff99\'>1.5</FONT>초마다 <FONT COLOR=\'#00ccff\'>605,252</FONT>의 [성] 속성 피해를 <FONT COLOR=\'#ffff99\'>3</FONT>회 주지만, 이동을 하면 시전이 취소된다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>재사용 대기시간이 <FONT COLOR=\'#99ff99\'>5.0</FONT>초 감소한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>빠른 준비</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_56.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>스킬 유지 중 피격이상에 면역이 된다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>안정된 빛</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_23.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>적에게 주는 피해가 <FONT COLOR=\'#ff9999\'>50.0%</FONT> 감소하지만, 빛의 광시곡 시전 중 받는 피해가 <FONT COLOR=\'#99ff99\'>50.0%</FONT> 감소한다.<BR>범위 안에 있는 자신을 제외한 파티원이 받는 피해를 <FONT COLOR=\'#ffff99\'>3.0</FONT>초간 <FONT COLOR=\'#99ff99\'>75.0%</FONT> 감소시키고, 자신의 최대 생명력의 <FONT COLOR=\'#99ff99\'>15.0%</FONT>까지 흡수하는 보호막을 생성한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>빛의 보호</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_65.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#F99200\'>수호</FONT>] 스킬 시전 중 자신의 최대 생명력의 12% 보호막을 획득"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>빛의 광시곡</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  },\r\n  "Element_009": {\r\n    "type": "BlinkLineStart",\r\n    "value": true\r\n  },\r\n  "Element_010": {\r\n    "type": "SingleTextBox",\r\n    "value": "다음 스킬 레벨 11"\r\n  },\r\n  "Element_011": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 레벨</FONT> 55"\r\n  },\r\n  "Element_012": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#808080\'>필요 스킬 포인트 </FONT>6"\r\n  },\r\n  "Element_013": {\r\n    "type": "SingleTextBox",\r\n    "value": "마나 569 소모"\r\n  },\r\n  "Element_014": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>마우스 위치에 아름다운 선율의 음파를 소환해 <FONT COLOR=\'#ffff99\'>1.5</FONT>초마다 <FONT COLOR=\'#00ccff\'>658,266</FONT>의 [성] 속성 피해를 <FONT COLOR=\'#ffff99\'>3</FONT>회 주지만, 이동을 하면 시전이 취소된다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>부위 파괴 : 레벨 1</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_015": {\r\n    "type": "BlinkLineEnd",\r\n    "value": true\r\n  }\r\n}',
        },
        {
          character_name: '첫번째도구',
          skill_name: '윈드 오브 뮤직',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_6.png',
          skill_level: 14,
          type: '일반',
          skill_type: '0',
          cooldown: 18,
          mana_cost: 495,
          weak_point: 0,
          stagger: null,
          attack_type: '백 어택 슈퍼아머',
          is_counter: false,
          tripod_1_name: '빠른 준비',
          tripod_2_name: '선율 증가',
          tripod_3_name: '수호의 바람',
          rune_name: '풍요',
          rune_grade: '영웅',
          tooltip:
            '{\r\n  "Element_000": {\r\n    "type": "NameTagBox",\r\n    "value": "윈드 오브 뮤직"\r\n  },\r\n  "Element_001": {\r\n    "type": "CommonSkillTitle",\r\n    "value": {\r\n      "leftText": "<FONT SIZE=\'12\'>재사용 대기시간 18초</FONT>",\r\n      "level": "<FONT SIZE=\'12\'><FONT COLOR=\'#B7DEE8\'><FONT COLOR=\'#F6F6F6\'>[일반 스킬]</FONT></FONT></FONT>",\r\n      "middleText": "",\r\n      "name": "<FONT SIZE=\'12\'><FONT SIZE=\'14\' COLOR=\'#FFFFAC\'>일반</FONT></FONT>",\r\n      "slotData": {\r\n        "iconGrade": 0,\r\n        "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/bd_skill/bd_skill_01_6.png",\r\n        "imagePath": ""\r\n      }\r\n    }\r\n  },\r\n  "Element_002": {\r\n    "type": "MultiTextBox",\r\n    "value": "|<FONT COLOR=\'#3C78FF\'>PvE</FONT>"\r\n  },\r\n  "Element_003": {\r\n    "type": "SingleTextBox",\r\n    "value": "스킬 레벨 14"\r\n  },\r\n  "Element_004": {\r\n    "type": "MultiTextBox",\r\n    "value": "마나 495 소모|"\r\n  },\r\n  "Element_005": {\r\n    "type": "SingleTextBox",\r\n    "value": "<FONT COLOR=\'#efefdf\'><FONT SIZE=\'11\'>강렬한 바람을 불러내 근접한 적에게 <FONT COLOR=\'#00ccff\'>245,249</FONT>의 피해를 주고 밀어내고, 바람이 넓게 퍼져나가 <FONT COLOR=\'#ffff99\'>1m</FONT> 추가 범위 내의 적에게 <FONT COLOR=\'#00ccff\'>367,614</FONT>의 피해를 준다.</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>공격 타입 : 백 어택</FONT></FONT><BR><FONT SIZE=\'12\'><FONT COLOR=\'#EEA839\'>슈퍼아머 : 경직 면역</FONT></FONT>"\r\n  },\r\n  "Element_006": {\r\n    "type": "TripodSkillCustom",\r\n    "value": {\r\n      "Element_000": {\r\n        "desc": "<font color=\'#FFFDE7\'>재사용 대기시간 <FONT COLOR=\'#99ff99\'>4.0</FONT>초 감소한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>빠른 준비</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_1_56.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_001": {\r\n        "desc": "<font color=\'#FFFDE7\'>윈드 오브 뮤직으로 회복하는 세레나데 게이지가 <FONT COLOR=\'#99ff99\'>225.0%</FONT> 증가한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>선율 증가</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_2_64.png",\r\n          "imagePath": ""\r\n        }\r\n      },\r\n      "Element_002": {\r\n        "desc": "<font color=\'#FFFDE7\'>시전 시 자신 및 윈드 오브 뮤직에 적중된 파티원에게 <FONT COLOR=\'#ffff99\'>4.0</FONT>초간 자신의 최대 생명력의 <FONT COLOR=\'#99ff99\'>30.0%</FONT>까지 흡수하는 보호막을 생성한다.</font>",\r\n        "lock": false,\r\n        "name": "<font color=\'#FFBB63\'>수호의 바람</font>",\r\n        "slotData": {\r\n          "iconGrade": 10,\r\n          "iconPath": "https://cdn-lostark.game.onstove.com/efui_iconatlas/tripod_tier/tripod_tier_3_75.png",\r\n          "imagePath": ""\r\n        }\r\n      }\r\n    }\r\n  },\r\n  "Element_007": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>스킬 룬 효과</FONT>",\r\n      "Element_001": "[<FONT COLOR=\'#ce43fc\'>풍요</FONT>] 스킬 적중 시 아이덴티티 게이지 획득량 30% 증가"\r\n    }\r\n  },\r\n  "Element_008": {\r\n    "type": "ItemPartBox",\r\n    "value": {\r\n      "Element_000": "<FONT COLOR=\'#A9D0F5\'>보석 효과</FONT>",\r\n      "Element_001": "[바드] <FONT COLOR=\'#FFD200\'>윈드 오브 뮤직</FONT> 재사용 대기시간 20.00% 감소 "\r\n    }\r\n  }\r\n}',
        },
      ],
      armory_gem_effects_tb: [
        {
          character_name: '첫번째도구',
          description: '기본 공격력 총합 : 9.40%',
        },
      ],
      armory_gem_tb: [
        {
          character_name: '첫번째도구',
          slot: 0,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '사운드 홀릭',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 1,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '윈드 오브 뮤직',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 2,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '소나티네',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 3,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '빛의 광시곡',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 4,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '음파 진동',
          effect_type: '피해 40.00% 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 5,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '천상의 연주',
          effect_type: '피해 40.00% 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 6,
          name: '9레벨 겁화의 보석',
          grade: '유물',
          level: 9,
          skill_name: '세레나데 스킬',
          effect_type: '지원 효과 9.00 % 증가',
          effect_option: '기본 공격력 1.00% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_104.png',
        },
        {
          character_name: '첫번째도구',
          slot: 7,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '수호의 연주',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 8,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '천상의 연주',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 9,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '리듬 벅샷',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
        {
          character_name: '첫번째도구',
          slot: 10,
          name: '8레벨 작열의 보석',
          grade: '유물',
          level: 8,
          skill_name: '음파 진동',
          effect_type: '재사용 대기시간 20.00% 감소',
          effect_option: '기본 공격력 0.80% 증가',
          icon: 'https://cdn-lostark.game.onstove.com/efui_iconatlas/use/use_12_113.png',
        },
      ],
    },
  },
};
